
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kaews
 */
public class Assignment1 extends javax.swing.JFrame {

    /**
     * Creates new form Assignment1
     */
    public static int[] array; //สร้างอาเรย์ไว้เก็บค่า int 

    public Assignment1() {
        initComponents();
        this.setTitle( "Save & Load Array–0712345 Mr.One Nottwo" ); // set title 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_1 = new javax.swing.JTextField();
        jText_2 = new javax.swing.JTextField();
        gen = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText_1.setText("jTextField1");

        jText_2.setText("jTextField1");

        gen.setText("Generate");
        gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Load");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jText_1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                    .addComponent(jText_2))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(gen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gen))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void genActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genActionPerformed
        // TODO add your handling code here:
        array = new int[10]; //สร้างอาเรย์ขนาด 10 ช่อง
        for (int i = 0; i < array.length; i++) { // loop เท่ากับ ขนาดของ array
            array[i] = genInt(1, 100); //set ค่าในอาเรย์ดด้วยการเรียกใช้ method genInt
        }
        System.out.println(Arrays.toString(array)); //print มาดู
        jText_1.setText(Arrays.toString(array)); //set ไว้ใน jtext ด้วยการแปลงarray เป็น string ด้วย Arrays.toString มีหลายวิธีแค่ยกตัวอย่างวิธีนี้
    }//GEN-LAST:event_genActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        saveFile(); //เรียกใช้ method savefile
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        load0Flie(); //เรียกใช้ method loadfile
        jText_2.setText(Arrays.toString(array)); //set ไว้ใน jtext ด้วยการแปลงarray เป็น string ด้วย Arrays.toString มีหลายวิธีแค่ยกตัวอย่างวิธีนี้
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assignment1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assignment1().setVisible(true);
            }
        });
    }

    private int genInt(int begin, int end) {// begin เริ่มต้น,  end จุดจบ
        Random random = new Random(); //เรียกใช้ Random ผ่านตัวแปร random
        return random.nextInt(end) + begin; // สุ่มเลขที่มีจุดเริ่มต้นตั้งแต่ begin - end
    }

    private void saveFile() {
        //--->>> save ออกมาเป็น .txtจะได้ไฟล์ ไปเปิดดูได้
        if (array != null) {//if(ต้องมีข้อมูลนะ ถึงจะ save)
            try {
                FileOutputStream fos = new FileOutputStream("data.txt");//ใน "ชื่อไฟล์.txt" เปลี่ยนตามโจทย์เลย
                ObjectOutputStream oos = new ObjectOutputStream(fos);
                oos.writeObject(array);//ใส่ข้อมูลที่ต้องการ save 
                oos.close();
                fos.close();
                //ปิดฟังก์ชั่นที่ใช้ในการ save
                /* JOptionPane.showMessageDialog(this,
                        "Successfully saved data (" + data.length + " records) to 'Data.ser'",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE);*/
            } catch (Exception e) {//ถ้า save ไม่ได้ด้วยประการทั้งปวงไม่ว่าสาเหตุใดๆก็ตามจะทำคำสั่งใน catch
                System.out.println(e);//print error มาดู
                //>>>ทำให้มัหน้าต่างแจ้งว่า error อะไร 
                JOptionPane.showMessageDialog(this,
                        e,
                        "Error",
                        JOptionPane.WARNING_MESSAGE);
                //<<<
            }
        } else {/*จะแสดงข้อความ 
                    "Please press the 'Generate' button first"
                    "No data"
                   ว่าให้ใส่กดปุ่ม Gen เพื่อให้มี data
             */
            JOptionPane.showMessageDialog(this,
                    "Please press the 'Generate' button first",
                    "No data",
                    JOptionPane.WARNING_MESSAGE);
        }
        //<<<---
        }
    private void load0Flie() {
        try {//การ load 
            FileInputStream fis = new FileInputStream("data.txt");//ชื่อไฟล์ที่เดียวกับที่ save 
            ObjectInputStream ois = new ObjectInputStream(fis);
            array = (int[]) ois.readObject();// cacth ด้วย type ของ array of int ที่ save แล้วใส่ไว้ใน array สร้างเป็นแบบ static ที่มีตัวเดียวในไฟล์นี้
            ois.close();
            fis.close();
            //ปิดฟังก์ชั่นที่ใช้ในการ load

            /*JOptionPane.showMessageDialog(this,
                    "Successfully load data (" + temp.length + " records) from 'Data.ser'",
                    "Info",
                    JOptionPane.INFORMATION_MESSAGE);*/
        } catch (Exception e) {//ถ้าเกิด error ขึ้นมามันจะแสดงหน้าต่างว่า error อะไรในหน้าต่างใหม่
            JOptionPane.showMessageDialog(this,
                    e,
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jText_1;
    private javax.swing.JTextField jText_2;
    // End of variables declaration//GEN-END:variables
}
